export const DISPLAY_ITEMS = 'DISPLAY_ITEMS';
export const ADD_PRINT_CART = 'ADD_PRINT_CART';
export const INCREASE_CART_NUMBER = 'INCREASE_CART_NUMBER'; 
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const DISPLAY_FORM = 'DISPLAY_FORM';
